# https://www.home-assistant.io/integrations/default_config/
default_config:

# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    # reolink_aio: debug
    custom_components.reolink_extras: debug

debugpy:
  # wait: true
